spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/jobOffer-web
      auto-index-creation: true
jobOffer:
  offer-fetchable:
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057
http:
  offers:
    scheduler:
      request:
        delay: PT3H


scheduling:
  enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
