spring:
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/jobOffer-web
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:63792}
jobOffer:
  offer-fetchable:
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          connectionTimeout: 1000
          readTimeout: 1000
          port: 5057
http:
  offers:
    scheduler:
      request:
        delay: PT3H

logging:
  level:
    org:
      springframework:
        security: DEBUG

scheduling:
  enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: job-offers-backend